trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform
  jobs:
  - job: InitPlan
    steps:

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.7.5'

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        backendServiceArm: 'azure-devops-connection'
        backendAzureRmResourceGroupName: 'NCPL'
        backendAzureRmStorageAccountName: 'ananthup2'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.terraform.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
