trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform_Init_Plan
  displayName: Terraform Init Plan

  jobs:
  - job: InitPlan
    displayName: Init Plan

    steps:

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: Terraform Init-Dev
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        backendServiceArm: 'azure-devops-connection'
        backendAzureRmOverrideSubscriptionID: '9ed6a571-7684-46a1-916a-dc19077389ae'
        backendAzureRmResourceGroupName: 'NCPL'
        backendAzureRmStorageAccountName: 'ananthup2'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.terraform.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        environmentServiceNameAzureRM: 'azure-devops-connection'